name: Install tools with cargo-binstall

inputs:
  args:
    required: true

runs:
  using: composite
  steps:
    - run: bash --version
      shell: bash

    - name: Install cargo-binstall *
      run: |
        BIN_DIR=/tmp/cargo-binstall
        case "$OS" in
          Windows)
            URL_SUFFIX=x86_64-pc-windows-msvc.zip
            EXE_SUFFIX=.exe;;
          macOS)
            URL_SUFFIX=x86_64-apple-darwin.zip
            EXE_SUFFIX=;;
          Linux)
            URL_SUFFIX=x86_64-unknown-linux-musl.tgz
            EXE_SUFFIX=;;
        esac
        URL="https://github.com/ryankurte/cargo-binstall/releases/latest/download/cargo-binstall-$URL_SUFFIX"
        ARCHIVE_EXT="${URL##*.}"
        ARCHIVE_PATH="/tmp/cargo-binstall.$ARCHIVE_EXT"

        mkdir -p "$BIN_DIR"
        curl --proto =https --tlsv1.2 -fL --retry 10 --retry-connrefused "$URL" -o "$ARCHIVE_PATH"
        case "$ARCHIVE_EXT" in
          zip) 7z x "$ARCHIVE_PATH" "-o$BIN_DIR";;
          tgz) tar xvf "$ARCHIVE_PATH" -C "$BIN_DIR";;
        esac
        rm "$ARCHIVE_PATH"
        export PATH="$BIN_DIR:$PATH"
        echo "Installed $BIN_DIR/cargo-binstall$EXE_SUFFIX" >&2

        jq '.[]' -c <<<"$ARGS" | while read -r arg; do
          crate="$(jq .crate -r <<<"$arg")"
          version="$(jq .version -r <<<"$arg")"
          pkg_url="$(jq .pkg_url -r <<<"$arg")"
          pkg_fmt="$(jq .pkg_fmt -r <<<"$arg")"
          RUST_LOG=cargo_binstall cargo binstall "$crate" --version "$version" --pkg-url "$pkg_url" --pkg-fmt "$pkg_fmt" --no-confirm
        done
      shell: bash
      env:
        OS: ${{ runner.os }}
        ARGS: ${{ inputs.args }}
