name: Install tools with cargo-binstall

inputs:
  args:
    required: true

runs:
  using: composite
  steps:
    - run: bash --version
      shell: bash

    - name: Install cargo-binstall *
      run: |
        case "$OS" in
          Windows) cargo_binstall_url_suffix=x86_64-pc-windows-msvc.zip;;
          macOS)   cargo_binstall_url_suffix=x86_64-apple-darwin.zip;;
          Linux)   cargo_binstall_url_suffix=x86_64-unknown-linux-musl.tgz;;
        esac
        cargo_binstall_url="https://github.com/ryankurte/cargo-binstall/releases/latest/download/cargo-binstall-$cargo_binstall_url_suffix"
        cargo_binstall_archive_ext="${cargo_binstall_url_suffix##*.}"

        cargo_binstall_tempdir="$(mktemp -d cargo-binstall-XXXXXXXX)"
        trap 'rm -r "$cargo_binstall_tempdir"' EXIT

        cargo_binstall_archive_path="$cargo_binstall_tempdir/cargo-binstall.$cargo_binstall_archive_ext"

        curl --proto =https --tlsv1.2 -fL --retry 10 --retry-connrefused "$cargo_binstall_url" -o "$cargo_binstall_archive_path"
        case "$cargo_binstall_archive_ext" in
          zip) 7z x "$cargo_binstall_archive_path" "-o$cargo_binstall_tempdir";;
          tgz) tar xvf "$cargo_binstall_archive_path" -C "$cargo_binstall_tempdir";;
        esac
        export PATH="$cargo_binstall_tempdir:$PATH"
        echo "Installed $(command -v cargo-binstall)" >&2

        jq '.[]' -c <<<"$ARGS" | while read -r arg; do
          crate="$(jq .crate -r <<<"$arg")"
          version="$(jq .version -r <<<"$arg")"
          pkg_url="$(jq .pkg_url -r <<<"$arg")"
          pkg_fmt="$(jq .pkg_fmt -r <<<"$arg")"
          bin_dir="$(jq .bin_dir -r <<<"$arg")"
          cargo binstall \
            "$crate" \
            --version "$version" \
            --pkg-url "$pkg_url" \
            --pkg-fmt "$pkg_fmt" \
            --bin-dir "$bin_dir" \
            --log-level debug \
            --min-tls-version 1.2 \
            --no-confirm
        done
      shell: bash
      env:
        OS: ${{ runner.os }}
        ARGS: ${{ inputs.args }}
